[tool.poetry]
name = "pystreams"
version = "0.1.0"
description = "python streaming helpers ğŸ"
readme = "README.md"
authors = ["radio-aktywne <it@radioaktywne.pl>"]
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent"
]
repository = "https://github.com/radio-aktywne/pystreams"
documentation = "https://radio-aktywne.github.io/pystreams"

[tool.poetry.dependencies]
python = "^3.9"
ffmpeg-generator = "^1.0"
numpy = "^1.22"

# dev

# test
pytest = { version = "^7.0", optional = true }

[tool.poetry.extras]
# need to do it that way until poetry supports dependency groups: https://github.com/python-poetry/poetry/issues/1644
dev = ["pytest"]
test = ["pytest"]

[build-system]
# this should be there, see https://python-poetry.org/docs/pyproject/#poetry-and-pep-517
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
